//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nubud.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nubud.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我们暂时不能处理该链接指向的内容，请稍后再试.
        /// </summary>
        public static string AddError {
            get {
                return ResourceManager.GetString("AddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加新链接.
        /// </summary>
        public static string AddUrl {
            get {
                return ResourceManager.GetString("AddUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 归档.
        /// </summary>
        public static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已归档.
        /// </summary>
        public static string Archived {
            get {
                return ResourceManager.GetString("Archived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文章列表.
        /// </summary>
        public static string Articles {
            get {
                return ResourceManager.GetString("Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题设置.
        /// </summary>
        public static string ChooseTheme {
            get {
                return ResourceManager.GetString("ChooseTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空缓存.
        /// </summary>
        public static string ClearCache {
            get {
                return ResourceManager.GetString("ClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缓存清理完毕.
        /// </summary>
        public static string ClearCacheMessage {
            get {
                return ResourceManager.GetString("ClearCacheMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公司网址：.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.generpoint.com.
        /// </summary>
        public static string CompanySite {
            get {
                return ResourceManager.GetString("CompanySite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认密码.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深色.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nubud是一款稍后阅读类应用，类似于Android和IOS平台的Pocket应用。她集中于分析和抓取给定链接指定的内容，并加以过滤和调整，为你带来更好的阅读体验。.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮箱地址和密码不能为空.
        /// </summary>
        public static string EmptyError {
            get {
                return ResourceManager.GetString("EmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duan112358@gmail.com.
        /// </summary>
        public static string FeedbackTo {
            get {
                return ResourceManager.GetString("FeedbackTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 谢谢使用Nubud. 这是字体大小阅览（This is current font size preview）. .
        /// </summary>
        public static string FontSample {
            get {
                return ResourceManager.GetString("FontSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置文章的字体大小.
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通用.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮箱地址不正确.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL格式不正确，请填写以http://或https://开头的链接地址.
        /// </summary>
        public static string InvalidUrl {
            get {
                return ResourceManager.GetString("InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大.
        /// </summary>
        public static string Large {
            get {
                return ResourceManager.GetString("Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浅色.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登陆.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮箱或密码错误.
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有Nubud账户？.
        /// </summary>
        public static string LoginHelperText {
            get {
                return ResourceManager.GetString("LoginHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出登录.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法建立网络连接，请检查你的网络设置.
        /// </summary>
        public static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前文章内容还没有被下载，要继续阅读，请打开网络链接.
        /// </summary>
        public static string NotCached {
            get {
                return ResourceManager.GetString("NotCached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nubud.
        /// </summary>
        public static string Nubud {
            get {
                return ResourceManager.GetString("Nubud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 官方网站：.
        /// </summary>
        public static string Offical {
            get {
                return ResourceManager.GetString("Offical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://beta.nubud.net.
        /// </summary>
        public static string OfficalSite {
            get {
                return ResourceManager.GetString("OfficalSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 源文章.
        /// </summary>
        public static string Original {
            get {
                return ResourceManager.GetString("Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码和确认密码不一致.
        /// </summary>
        public static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 阅读.
        /// </summary>
        public static string Reading {
            get {
                return ResourceManager.GetString("Reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有Nubud账户  ?.
        /// </summary>
        public static string RegisterHelperText {
            get {
                return ResourceManager.GetString("RegisterHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zh-CN.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分享.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小.
        /// </summary>
        public static string Small {
            get {
                return ResourceManager.GetString("Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出错了。。。.
        /// </summary>
        public static string SomethingWrong {
            get {
                return ResourceManager.GetString("SomethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作成功.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消归档.
        /// </summary>
        public static string UnArchive {
            get {
                return ResourceManager.GetString("UnArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://beta.nubud.com.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮箱.
        /// </summary>
        public static string YourEmail {
            get {
                return ResourceManager.GetString("YourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码.
        /// </summary>
        public static string YourPassword {
            get {
                return ResourceManager.GetString("YourPassword", resourceCulture);
            }
        }
    }
}
